kind: Service
apiVersion: v1
metadata:
  labels:
    app: gs-webui
    version: 12.1.0
  name: gs-webui
spec:
  ports:
    - port: 8099
      targetPort: 8099
      nodePort: 30099
      protocol: TCP
  selector:
    app: gs-webui
    version: 12.1.0
  type: NodePort